### ISSUE TITLE
Neko 2.1.0 packages

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/neko#127]
- [x] Chocolatey ([done](https://chocolatey.org/packages/neko/2.1.0))
- [x] homebrew (https://github.com/Homebrew/homebrew-core/pull/982)
- [x] Debian (https://packages.debian.org/sid/neko)
- [x] HF PPA
- [x] Fedora
- [x] openSUSE (blocked by https://bugzilla.opensuse.org/show_bug.cgi?id=980196) (https://build.opensuse.org/request/show/437869)
- [x] Arch Linux (flagged [existing package](https://www.archlinux.org/packages/community/i686/neko/) as outdated)
- [x] TravisCI default Neko version (https://github.com/travis-ci/travis-build/pull/730) #

**Comment by fulopm** [comment]
@andyli, Will the Debian weezy version get updated to 2.1.0? With the current version (1.8.1-6+b1 armfh) I can't run programs compiled with Haxe 3.2.1.

Thanks!

**Comment by andyli** [comment]
Just use the unstable(sid) packages. The haxe.org download page of linux
packages has some instruction.

**Comment by fulopm** [comment]
Unfortunately this is impossible, because if I install something from the unstable, the dependencies will be broken...
For example:
`pi@raspberrypi ~ $ sudo apt-get -t unstable install neko -y -q
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libdbus-1-3 : Breaks: dbus (< 1.9.16-1~) but 1.6.8-1+deb7u6 is to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
`

**Comment by fulopm** [comment]
Never mind, I'll install Fedora to get the latest releases (as I seen, there are up-to-date versions on the stable branches). Thanks for the advise though!
