### ISSUE TITLE
exec format error: nekotools

### ISSUE THREAD

**Issue by xyproto** [HaxeFoundation/neko#131]
Hi,

I'm trying to pakage neko 2.1.0 for Arch Linux.

Using CMake works great (thanks for switching over!), but when running the resulting binaries, there are issues:

```
% nekoml
zsh: exec format error: nekoml

% strace nekoml
execve("/usr/bin/nekoml", ["nekoml"], [/* 76 vars */]) = -1 ENOEXEC (Exec format error)
write(2, "strace: exec: Exec format error\n", 32strace: exec: Exec format error
) = 32
exit_group(1)                           = ?
+++ exited with 1 +++
```

This happens for `nekoc`, `nekoml` and `nekotools`, but not `neko`.

I'm using the default CMake definitions, except from the usual `-DCMAKE_INSTALL_PREFIX=/usr` and `-DCMAKE_INSTALL_LIBDIR=lib`.

Here is the [complete PKGBUILD file](https://git.archlinux.org/svntogit/community.git/plain/trunk/PKGBUILD?h=packages/neko&id=462cadd38a85d2d49a8bde9f0c91545acad4562b).

I'm on 64-bit Arch Linux.

**Comment by andyli** [comment]
`nekoc`, `nekoml` and `nekotools` are built using `nekotools boot`, which concatenates the `neko` binary with some neko bytecode. It then try to "fix" the ELF headers with clever tricks and maybe that causes the issue.

Would you try apply a8c71ad97faaccff6c6e9e09eba2d5efd022f8dc (as a [patch](https://github.com/HaxeFoundation/neko/commit/a8c71ad97faaccff6c6e9e09eba2d5efd022f8dc.patch))? It builds `nekoc`, `nekoml` and `nekotools` using C instead of messing with the binary format.

More details: https://github.com/HaxeFoundation/neko/issues/130

**Comment by xyproto** [comment]
Will try the patch, thanks!

**Comment by andyli** [comment]
Oh, I think you will need to apply fe87462d9c7a6ee27e28f5be5e4fc0ac87b34574 as well. Please let me know if there is still other problems.

**Comment by andyli** [comment]
Closing since I can see neko 2.1 is available at https://www.archlinux.org/packages/?sort=&q=neko&maintainer=&flagged=
Thanks, xyproto!

**Comment by xyproto** [comment]
Sorry for not coming back to you when I got it working, I forgot.

Everything seems to work fine when only passing `-DRUN_LDCONFIG=OFF` to CMake.

Thanks!
