### ISSUE TITLE
Calling free_root inside finalizer causes neko to crash

### ISSUE THREAD

**Issue by vroad** [HaxeFoundation/neko#138]
Is it not allowed to call free_root inside finalizer function? Then, How can I free C++ object stored in an abstract value that depends on another C++ object?

I did this because I wanted to free OpenGL textures automatically even when a programmer forget to delete them. OpenGL textures neeed to have a reference to OpenGL context, so that it can be deleted correctly when multiple contexts are used. I used hxCFFI's AutoGCRoot for this, but this caused heap corruption only on neko. On cpp and cs this just works fine.

**Comment by ncannasse** [comment]
Sadly this is part of the Boehm GC code, not neko code. Please report it there https://github.com/ivmai/bdwgc

**Comment by hughsando** [comment]
Are you deleting your own GC root from the finalizer, or another objects?
You could set the value to null before deleting the AutoGCRoot, which should free the root, and allow the data to be reclaimed in the next collection.

**Comment by vroad** [comment]
I tried to release reference of another object, but didn't work for some reason. I've also found that freeing AutoGCRoot in other places works correctly. So there should be another reason why this doesn't work.

I'm not sure what Hugh is saying. Shouldn't roots be always freed with free_root?

I could avoid this problem by reference counting another C++ object, without using AutoGCRoot. This may not be enough for complex use cases, but for my case this was enough.

**Comment by hughsando** [comment]
So even if you free the root, the collector has already run and marked the object as "used", so it wont collect it this pass no matter what you do.  So I was thinking that by setting the root to null, it would not cause boehmgc to crash.  Although, now I think about it, it might not solve the problem, since it is the pointer-to-pointer that needs freeing.

Anyhow, I think you are going to want to pass the value over to the main thread to clean opengl resources (can't rely on the thread doing the finalization), so you could clean up the associated roots in there instead.

So say you had a "glProgram" struct with 2 glShader roots, you would add the glProgram to the "toBeFree" list in the finalizer.  Then, on next refresh (or next resource allocation) from the main thread, you would dispose of the gl resource and release the roots.

This is similar to what nme does, although this relies on haxe to have references to keep haxe object alive.
Nme also uses reference counting, where gc roots have a reference count, but native objects can have native reference counts too.

https://github.com/haxenme/nme/blob/master/project/src/opengl/OGLExport.cpp#L263
https://github.com/haxenme/nme/blob/master/project/src/opengl/OpenGLContext.cpp#L117
