### ISSUE TITLE
Neko memory Leak when use socket readClientMessage

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/neko#179]
Neko Memory Leak when use socket readClientMessage

hi,current I test neko ThreadServer,and found when I send a zip file use socket , zip file size is 20MB
and neko*32   memory Leak
![image](https://user-images.githubusercontent.com/748320/41017743-dfff8fdc-6988-11e8-86f0-e6c431a6062b.png)
![image](https://user-images.githubusercontent.com/748320/41017769-fbfcaa12-6988-11e8-906f-8311937b942e.png)

haxe 4.0 preview 3
neko version  2.0

**Comment by andyli** [comment]
You may try calling [`neko.vm.Gc.run()`](https://api.haxe.org/neko/vm/Gc.html) a few times and see if is able to free some memory. If it does, it is not really a memory leak, since the GC will eventually run and free that memory (without the manual use of `neko.vm.Gc.run()`).

If the memory consumption doesn't go down, please provide a minimal example without any external dependency and we will take a look.

**Comment by sonygod** [comment]
ok,I'll sent you a minimal example soon

**Comment by sonygod** [comment]
[testneko.zip](https://github.com/HaxeFoundation/neko/files/2075433/testneko.zip)
@andyli  here is my example

**Comment by tour1st** [comment]
Sorry to bump an old issue, but I have the same problem on my server when targeting Neko.
Calling `neko.vm.Gc.run()` doesn't fix it, and the issue is still present in Neko 2.3.
@sonygod Did you find a workaround to fix these memory leaks ?

**Comment by sonygod** [comment]
@tour1st , no, but I use Hashlink instead of Neko for my server engine.seem everything is well.
