### ISSUE TITLE
Uncaught exception - load.c(398) : Invalid module : unit.n

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/neko#70]
I hate that error so much. Can we make `neko_read_module` set some error state or something and output that instead?

I'm willing to look into it if you tell me how to approach it.

**Comment by ncannasse** [comment]
you can printf the __LINE__ in the ERROR() define in vm/module.c

**Comment by ncannasse** [comment]
that helps to debug I'm not sure how to handle a more explicit error given it's actually not supposed to happen

**Comment by Simn** [comment]
Oh boy, I have it failing in line 573 which means `neko_check_stack`...

**Comment by waneck** [comment]
This may mean simply that the stack is too big. We really need better error
reporting there.

**Comment by ncannasse** [comment]
Did you manage to fix this one @Simn ?

**Comment by ncannasse** [comment]
No feedback, closing

**Comment by Simn** [comment]
I fixed the original cause (some Haxe bug) so I no longer had a need for this. It would still be nice to have better errors in neko, but that's a quite general problem.

**Comment by frabbit** [comment]
I ran into this quite often while doing that unicode stuff, very hard to debug.

**Comment by frabbit** [comment]
it was also the stack related.

**Comment by player-03** [comment]
I'm getting this error all the time now. It makes Neko unusable in nearly all cases. Fortunately I don't need Neko for anything, but I figured I'd document this anyway.

My issues seem to be based on the number of classes (or maybe class methods) compiled into the app. If I keep the app under ~10-15 classes, it works fine, but if I add one too many imports, suddenly the module is invalid. I don't even have to use the imports for it to happen. (Also none of the classes have any kind of static initialization, and I do have DCE enabled.)

So yeah, weird bug. Maybe it's something wrong with my installation (though I did reinstall Haxe already, with no effect). Or maybe it's because Neko is no longer supported, and something like this was bound to happen eventually. In any case, HashLink works fine and that's good enough for me.

**Comment by flashultra** [comment]
It's the same error for me too. I tested with the [Neko 2.2.0](https://github.com/HaxeFoundation/crypto/actions/runs/3141080557/jobs/5103133273#step:11:35 )    and [Neko 2.3.1 ](https://github.com/HaxeFoundation/crypto/actions/runs/3138514743/jobs/5097927545#step:13:41) and the result is the same : 
```Uncaught exception - load.c(398) : Invalid module : bin/unit.n```
